#!/bin/bash
if [ "$1" = "-d" ]; then
    echo "Deploying website to development server"
    rsync -av --delete --exclude='deploy' --exclude='*~' --exclude='*.swp' --exclude='.git' . /var/www
elif [ "$1" = "-p" ]; then
    rsync -avze ssh --delete --exclude='deploy' --exclude='*~' --exclude='*.swp' --exclude='.git' . krisphar@174.136.13.224:www/subdomains/khph.info/
else
    echo "Usage: deploy [-d | -p]" >&2
    exit 1
fi
